### ISSUE TITLE
Weird go-mruby panic

### ISSUE THREAD

**Issue by errordeveloper** [errordeveloper/kubeplay#1]
```
> ./kubeplay -kubeconfig ~/.kube/config
kubeplay (namespace="*")> pods
+++ Execute: pods 
args=[]
0: extra/demo-3182697418-lr7w8
1: extra/launch-generator-42362003-3w5dp
2: kube-system/kube-addon-manager-minikube
3: kube-system/kube-dns-v20-rb15z
4: kube-system/kubernetes-dashboard-024nl
kubeplay (namespace="*")> pod "extra/"
+++ Error: undefined method 'pod' for main
kubeplay (namespace="*")> pods "extra/"
+++ Execute: pods extra/
args=[extra/]
0: extra/demo-3182697418-lr7w8
1: extra/launch-generator-42362003-3w5dp
kubeplay (namespace="*")> pods labels: "name"
+++ Execute: pods {:labels=>"name"}
args=[{:labels=>"name"}]
0: extra/demo-3182697418-lr7w8
1: extra/launch-generator-42362003-3w5dp
kubeplay (namespace="*")> pods {}
+++ Execute: pods 
args=[#<Proc:0x8801710@-:->]
0: extra/demo-3182697418-lr7w8
1: extra/launch-generator-42362003-3w5dp
2: kube-system/kube-addon-manager-minikube
3: kube-system/kube-dns-v20-rb15z
4: kube-system/kubernetes-dashboard-024nl
kubeplay (namespace="*")> pods []
+++ Execute: pods []
args=[[]]
fatal error: exitsyscall: syscall frame is no longer valid

runtime stack:
runtime.throw(0x50ced1c, 0x2d)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/runtime/panic.go:566 +0x95
runtime.exitsyscall.func1()
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/runtime/proc.go:2470 +0x36
runtime.systemstack(0x700007946e68)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/runtime/proc.go:1079

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4da1900, 0xc4205d5720, 0xc400000000)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/runtime/cgocall.go:131 +0x110 fp=0xc4205d56c8 sp=0xc4205d5688
github.com/errordeveloper/kubeplay/vendor/github.com/mitchellh/go-mruby._Cfunc_mrb_funcall_argv(0x7306b70, 0x8800ae0, 0x8, 0x100000297, 0xc420408550, 0x0, 0x0)
	??:0 +0x5d fp=0xc4205d5720 sp=0xc4205d56c8
github.com/errordeveloper/kubeplay/vendor/github.com/mitchellh/go-mruby.(*MrbValue).call(0xc4205966a0, 0x50a72ec, 0x4, 0xc420408530, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/github.com/mitchellh/go-mruby/value.go:96 +0x5a6 fp=0xc4205d5808 sp=0xc4205d5720
github.com/errordeveloper/kubeplay/vendor/github.com/mitchellh/go-mruby.(*MrbValue).Call(0xc4205966a0, 0x50a72ec, 0x4, 0xc420408530, 0x1, 0x1, 0xc420030078, 0xc420030078, 0xc420408510)
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/github.com/mitchellh/go-mruby/value.go:47 +0x7c fp=0xc4205d5870 sp=0xc4205d5808
github.com/errordeveloper/kubeplay/rubykube.(*podsClassInstance).Update(0xc420408510, 0xc420408530, 0x1, 0x1, 0x1, 0xc420408530, 0x0, 0x1)
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/rubykube/class.pods.go:343 +0x65 fp=0xc4205d58c8 sp=0xc4205d5870
github.com/errordeveloper/kubeplay/rubykube.pods(0xc4201f5480, 0xc420030070, 0x1, 0x1, 0xc420030068, 0xc420596600, 0x2, 0x40a4fc0, 0xc4203be610, 0x40a51a9)
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/rubykube/verbs.go:60 +0x185 fp=0xc4205d5950 sp=0xc4205d58c8
github.com/errordeveloper/kubeplay/rubykube.(*RubyKube).AddVerb.func1(0xc420030068, 0xc420596600, 0x28e, 0xc4203b9ca0, 0xc420408347, 0xc420408340)
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/rubykube/rubykube.go:109 +0x149 fp=0xc4205d59e8 sp=0xc4205d5950
github.com/errordeveloper/kubeplay/vendor/github.com/mitchellh/go-mruby.goMRBFuncCall(0x7306b70, 0x700007945cd8, 0x700007945cc8, 0x0, 0x0)
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/github.com/mitchellh/go-mruby/func.go:83 +0x248 fp=0xc4205d5ac0 sp=0xc4205d59e8
github.com/errordeveloper/kubeplay/vendor/github.com/mitchellh/go-mruby._cgoexpwrap_837d835d62ad_goMRBFuncCall(0x7306b70, 0x700007945cd8, 0x700007945cc8, 0x0, 0x0)
	??:0 +0x51 fp=0xc4205d5b08 sp=0xc4205d5ac0
runtime.call64(0x0, 0x700007945bc8, 0x700007945c68, 0x28)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/runtime/asm_amd64.s:480 +0x4c fp=0xc4205d5b58 sp=0xc4205d5b08
runtime.cgocallbackg1(0x0)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/runtime/cgocall.go:283 +0x19d fp=0xc4205d5bd0 sp=0xc4205d5b58
runtime.cgocallbackg(0xc4205d5c60)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/runtime/cgocall.go:170 +0x84 fp=0xc4205d5c38 sp=0xc4205d5bd0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/os/signal/signal_unix.go:28 +0x41

goroutine 34 [chan receive]:
github.com/errordeveloper/kubeplay/vendor/k8s.io/client-go/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x594d1e0)
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/k8s.io/client-go/vendor/github.com/golang/glog/glog.go:879 +0x7a
created by github.com/errordeveloper/kubeplay/vendor/k8s.io/client-go/vendor/github.com/golang/glog.init.1
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/k8s.io/client-go/vendor/github.com/golang/glog/glog.go:410 +0x21d

goroutine 8 [select]:
github.com/errordeveloper/kubeplay/vendor/github.com/chzyer/readline.(*Terminal).ioloop(0xc42048cfc0)
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/github.com/chzyer/readline/terminal.go:108 +0x298
created by github.com/errordeveloper/kubeplay/vendor/github.com/chzyer/readline.NewTerminal
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/github.com/chzyer/readline/terminal.go:33 +0x162

goroutine 9 [select, locked to thread]:
runtime.gopark(0x515b980, 0x0, 0x50a97ff, 0x6, 0x18, 0x2)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc4204f5f30, 0x0, 0x18)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc4204f5f30)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/runtime/signal1_unix.go:304 +0x2d1
runtime.goexit()
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/runtime/asm_amd64.s:2086 +0x1

goroutine 10 [chan receive]:
github.com/errordeveloper/kubeplay/vendor/github.com/chzyer/readline.DefaultOnWidthChanged.func1.1(0xc4202649c0)
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/github.com/chzyer/readline/utils_unix.go:82 +0x53
created by github.com/errordeveloper/kubeplay/vendor/github.com/chzyer/readline.DefaultOnWidthChanged.func1
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/github.com/chzyer/readline/utils_unix.go:88 +0xec

goroutine 11 [chan receive]:
github.com/errordeveloper/kubeplay/vendor/github.com/chzyer/readline.(*Operation).ioloop(0xc420264960)
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/github.com/chzyer/readline/operation.go:98 +0x61
created by github.com/errordeveloper/kubeplay/vendor/github.com/chzyer/readline.NewOperation
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/github.com/chzyer/readline/operation.go:82 +0x3f0

goroutine 12 [chan receive]:
github.com/errordeveloper/kubeplay/vendor/github.com/erikh/box/builder/signal.SetSignal.func1(0xc420230780, 0x0)
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/github.com/erikh/box/builder/signal/signal.go:20 +0x57
created by github.com/errordeveloper/kubeplay/vendor/github.com/erikh/box/builder/signal.SetSignal
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/github.com/erikh/box/builder/signal/signal.go:29 +0x155

goroutine 16 [IO wait]:
net.runtime_pollWait(0x7426ae8, 0x72, 0x3)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420184060, 0x72, 0xc420528808, 0xc420016220)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420184060, 0x58f34e0, 0xc420016220)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420184000, 0xc42062c000, 0x4000, 0x4000, 0x0, 0x58f34e0, 0xc420016220)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc4201e8008, 0xc42062c000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/net/net.go:173 +0x70
crypto/tls.(*block).readFromUntil(0xc4201b6150, 0x8221000, 0xc4201e8008, 0x5, 0xc4201e8008, 0x0)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/crypto/tls/conn.go:472 +0x91
crypto/tls.(*Conn).readRecord(0xc420152000, 0x515ba17, 0xc420152100, 0x0)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/crypto/tls/conn.go:574 +0xc4
crypto/tls.(*Conn).Read(0xc420152000, 0xc4200d6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/crypto/tls/conn.go:1109 +0x116
bufio.(*Reader).fill(0xc420264480)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc420264480, 0xc4201479b8, 0x9, 0x9, 0xc420528cb0, 0x403d700, 0x402a66c)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0x58ebea0, 0xc420264480, 0xc4201479b8, 0x9, 0x9, 0x9, 0xc4202e4160, 0xc420528d10, 0x4bd60c5)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/io/io.go:307 +0xa4
io.ReadFull(0x58ebea0, 0xc420264480, 0xc4201479b8, 0x9, 0x9, 0xc4203383c0, 0x50ad3a4, 0xa)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.7.1/libexec/src/io/io.go:325 +0x58
github.com/errordeveloper/kubeplay/vendor/k8s.io/client-go/vendor/golang.org/x/net/http2.readFrameHeader(0xc4201479b8, 0x9, 0x9, 0x58ebea0, 0xc420264480, 0x0, 0xc400000000, 0x4c600d7, 0xc420528f80)
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/k8s.io/client-go/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/errordeveloper/kubeplay/vendor/k8s.io/client-go/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc420147980, 0xc420338b40, 0x0, 0x0, 0x0)
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/k8s.io/client-go/vendor/golang.org/x/net/http2/frame.go:464 +0xa4
github.com/errordeveloper/kubeplay/vendor/k8s.io/client-go/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc420528f80, 0x515ae58, 0xc4204f3f90)
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/k8s.io/client-go/vendor/golang.org/x/net/http2/transport.go:1233 +0x97
github.com/errordeveloper/kubeplay/vendor/k8s.io/client-go/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc42045c9c0)
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/k8s.io/client-go/vendor/golang.org/x/net/http2/transport.go:1170 +0xa6
created by github.com/errordeveloper/kubeplay/vendor/k8s.io/client-go/vendor/golang.org/x/net/http2.(*Transport).NewClientConn
	/Users/ilya/Code/kubeplay/src/github.com/errordeveloper/kubeplay/vendor/k8s.io/client-go/vendor/golang.org/x/net/http2/transport.go:492 +0x89b

> 
```

**Comment by erikh** [comment]
OK, yeah. Please report this on mitchellh/go-mruby and attach code + panic please.
